<main>
    <table id="users">
        <thead>
            <tr>
                <td></td>
                <td>Pseudonyme</td>
                <td>Identité</td>
                <td>Mail</td>
                <td>Niveau d'accès</td>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($users as $index => $user) : ?>
                <tr>
                    <td><?= $index + 1 ?></td>
                    <td><?= $user['username'] ?></td>
                    <td><?= $user['firstname'] . " " . $user['lastname'] ?></td>
                    <td><?= $user['mail'] ?></td>
                    <td><?= $user['accesslevel'] ?><a href="#" title="Modifier"><i class="fas fa-key"></i></a></td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</main>