<header>
    <h1>Le blog de Pénélope et Michèle</h1>
    <nav id="firstNav">
        <a href="index.php">Accueil</a>
        <?php if ($_SESSION['authLevel'] > 1) : ?>
            <a href="new.php">Nouvel article</a>
            <a href="edit_form.php">Gestion du blog</a>
        <?php endif ?>
        <?php if (!$_SESSION['isConnected']) : ?>
            <a href="#" id="connectLink">Connexion</a>
            <a href="signup_form.php">Inscription</a>
        <?php endif ?>
    </nav>
    <nav id="secondNav">
        <?php if ($_SESSION['authLevel'] == 10) : ?><a href="administrate.php"><i class="fas fa-cogs"></i> Gestion des usagers</a><?php endif ?>
        <?php if ($_SESSION['isConnected']) : ?><a href="disconnect.php"><i class="fas fa-user-times"></i> Déconnexion (<?= $_SESSION['username'] ?>)</a><?php endif ?>
    </nav>
    <form action="connect.php" method="post" id="connectForm" style="display: none">
        <div>
            <label for="username">Identifiant : </label><input id="username" name="username" type="text">
        </div>
        <div>
            <label for="password">Mot de passe : </label><input id="password" name="password" type="password">
        </div>
        <div>
            <button>Connexion</button>
        </div>
    </form>
    <form style="margin-top: 10px" action="" method="post" id="colorForm">
        <input <?php if ($_COOKIE['color'] == "firebrick") : ?>checked<?php endif ?> type="radio" name="color" id="firebrick" value="firebrick">
        <input <?php if ($_COOKIE['color'] == "green") : ?>checked<?php endif ?> type="radio" name="color" id="green" value="green">
        <input <?php if ($_COOKIE['color'] == "steelblue") : ?>checked<?php endif ?> type="radio" name="color" id="steelblue" value="steelblue">
    </form>
    
    <script>
        <?php if (!$_SESSION['isConnected']) : ?>
        // Connection form toggle
        document.getElementById("connectLink").addEventListener("click", function(){
            if(document.getElementById("connectForm").style.display == "flex"){
                document.getElementById("connectForm").style.display = "none";
            } else {
                document.getElementById("connectForm").style.display = "flex";
            }
        });
        <?php endif ?>

        // Primary site color change
        document.getElementsByName("color").forEach(btn => btn.addEventListener("change", function(){
            document.getElementById("colorForm").submit();
        }))
    </script>
</header>