<main id="index">
    <aside>
        <?php foreach ($categories as $category) : ?>
        <a href="index.php?categ=<?= $category ?>"><?= $category ?></a>
        <?php endforeach ?>
    </aside>
    <section>
        <?php foreach ($data as $index => $article) : ?>
        <article id="<?= $index ?>">
            <h2><a href="article.php?art=<?= $article["id"] ?>"><?= $article["title"] ?></a></h2>
            <p><?= $article["content"] ?></p>
            <em><?= $article["type"] ?> - <?= $article["firstname"] . " " . $article["lastname"] . " - Le " . substr($article["creation_date"], 0, -8) . " à " . substr($article["creation_date"], -9, 6) ?><?php if ($article["modification_date"] != "") : echo " - Modifié le " . substr($article["modification_date"], 0, -8) . " à " . substr($article["modification_date"], -9, 6);
                                                                                                                                                                                                            endif ?></em>
        </article>
        <?php endforeach ?>
        <nav>
            <a data-id="1" href="index.php?page=1&direction=<?= $direction ?>&order=<?= $order ?>&categ=<?= $categ ?>">1</a>
            <?php for ($i = $page - 7; $i < $page + 7; $i++) : ?>
                <?php if ($i > 1 && $i < $maxPages) : ?>
                    <a data-id="<?= $i ?>" href="index.php?page=<?= $i ?>&direction=<?= $direction ?>&order=<?= $order ?>&categ=<?= $categ ?>"><?= $i ?></a>
                <?php endif ?>
            <?php endfor ?>
            <?php if ($maxPages != 1) : ?>
                 <a data-id="<?= $maxPages ?>" href="index.php?page=<?= $maxPages ?>&direction=<?= $direction ?>&order=<?= $order ?>&categ=<?= $categ ?>"><?= $maxPages ?></a>
            <?php endif ?>
        </nav>
    </section>

    <script>
        // Pagination links underlining
        document.querySelectorAll("a[data-id]").forEach(function(link){
            if(link.dataset.id == <?= $page ?>){
                link.style.textDecoration = "underline";
                link.style.color = "#851919";
            }
        });
    </script>
</main>