<main id="signup">
    <form action="signup.php" method="post">
        <label for="firstname">Prénom : </label><input id="firstname" name="firstname" type="text" value="">
        <label for="lastname">Nom : </label><input id="lastname" name="lastname" type="text" value="">
        <label for="mail">Votre e-mail :</label><input id="mail" name="mail" type="mail">
        <label for="username">Identifiant (20 caratères maximum): </label>
        <input id="username" name="username" type="text">
        <label for="password">Mot de passe : </label>
        <input id="password" name="password" type="password">
        <label for="passwordConfirm">Confirmez le mot de passe : </label>
        <input id="passwordConfirm" name="passwordConfirm" type="password">
        <button type="submit">M'inscrire</button>
    </form>
</main>